version = "2.0"

[sink_group]
name = "demo"
oml = ["*"]
tags = ["biz:demo"]

[[sink_group.sinks]]
name = "json"
connect = "file_json_sink"
tags = ["sink:json"]

[sink_group.sinks.params]
file = "demo.json"
