[package]
name = "wp-config"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "wp_conf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
winnow = { workspace = true }
orion-error = { workspace = true }
orion_conf = { workspace = true }
derive_more = { workspace = true }
wp_knowledge = { package = "wp-knowledge", path = "../wp-knowledge" }
orion_exp = { path = "../orion_exp" }
orion_overload= { path = "../orion_overload" }
wp_model_core = { workspace =true  }
wp_data_model = { workspace =true  }
wp-error =  { workspace = true }
wp-log =  { workspace = true }
wpl = { package = "wp-lang", path = "../wp-lang" }
wp-specs =  { workspace = true }
wp_conf_base = { workspace = true }
wp_connector_api ={ workspace=true }
async-trait = { workspace = true }
wp_parser = { package = "wp-parser", path = "../wp-parser" }
log = { workspace = true }
glob = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
educe = { workspace = true, features = [
    "Debug",
    "Default",
], default-features = false }
derive-getters = { workspace = true }
getset = { workspace = true }
once_cell = { workspace = true }
wildmatch = { workspace = true }
serde_derive = { workspace = true }
chrono = { workspace = true }
