[[connectors]]
id = "syslog_tcp_sink"
type = "syslog"
allow_override = ["addr", "port", "protocol"  ]
[connectors.params]
addr = "127.0.0.1"
port = 1514
protocol = "tcp"
strip_header = true
attach_meta_tags = true
tcp_recv_bytes = 10485760
