[package]
name = "orion_overload"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
derive-getters = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
